# Configurações de conexão com o SQLServer
bancos:
    server: 'FREDAO-NITRO\ANEELSERVER'
    database: 'GEO_SIGR_enelsp2022'
    username: 'usr_GeoPerdas'
    password: '123456'
    schema: 'SDE'

tipo_arquivo: "gdb"    # gbd ou dbf
dbf_directory: 'C:\Users\Pesquisador\Documents\BDGD\.dbfs\enelsp\2022\2_em_curso'

#gdb_directory: 'D:\\Doutorado\\PD\dados\\BDGD\\Energisa'
#gdb_file: 'Energisa_MS_404_2022-12-31_V11_20231219-1342.gdb'

gdb_directory: 'C:\Users\Pesquisador\Documents\BDGD\.gdbs'
gdb_file: 'ENEL_SP_390_2022-12-31_V11_20231024-1657.gdb'
data_base: "2022-12-31"
dist: '391'
cod_BDGD: '1657'

# diretório dos arquivos do openDSS (user folder)
dss_files_folder: '~\dss'